app:
  name: app_example
  version: 0.0.1
db:
  host: http://127.0.0.1:9200
github:
  repo:
    url: https://api.github.com/repos/vsouza/awesome-ios/git/trees/HEAD
    readme: README.md
  auth:
    app: app_example
    token: ----------
